Add initial circleci deployment steps

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -50,10 +50,43 @@ jobs:
       - run: bundle exec rake db:schema:load
 
       # run tests!
+      # if test = pass -> run Docker stuff
+      # if test = failed -> dont run Docker stuff
       - run:
           name: run tests
           command: |
             bundle exec rspec spec
+
+      # Docker stuff
+      - run:
+        name: Load Docker image layer cache
+        command: |
+          set +o pipefail
+          docker load -i /caches/app.tar | true
+      - run:
+        name: Build application Docker image
+        command: |
+          docker build --cache-from=app -t app .
+      - run:
+        name: Save Docker image layer cache
+        command: |
+          mkdir -p /caches
+          docker save -o /caches/app.tar app
+      - save_cache:
+        key: v1-{{ .Branch }}-{{ epoch }}
+        paths:
+          - /caches/app.tar
+
+      # TODO: Configure Docker hub login credentials
+      - deploy:
+        name: Push application Docker image
+        command: |
+          if [ "${CIRCLE_BRANCH}" == "master" ]; then
+            login="$(aws ecr get-login)"
+            ${login}
+            docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
+            docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
+          fi
 
       # collect reports
       - store_test_results:
